# Repository
repo_name: zoejane/music-mkdocs
repo_url: https://github.com/zoejane/music-mkdocs

site_name: Music
theme:
  name: material
nav:
    - Home: index.md
    - Piano: 
        - 笔记: pianonotes.md
        - 练习: pianopractice.md
    - Sing: sing.md
    - Playground: playground.md